### ISSUE TITLE
Tech Controlers integration not loaded

### ISSUE THREAD

**Issue by Tijn1974** [mariusz-ostoja-swierczynski/tech-controllers#20]
Since I upgraded to Home Assistant 2021.6.4 the Tech Controllers integration is not loaded. Even with a clean Home Assistant install (version 2021.6.4) the integration is not loaded.

The error message that appears: Setup failed for tech: Integration not found.

Is this a know issue?

Greetings,
Martijn

**Comment by nepozs** [comment]
It looks like missing version information in manifest.json

**Comment by nepozs** [comment]
Owner should do it, my suggestion is:
```
{
  "domain": "tech",
  "name": "Tech Controllers",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/tech",
  "version": "0.0.1",
  "requirements": ["tech"],
  "dependencies": [],
  "codeowners": [
    "@mariusz.ostoja-swierczynski"
  ]
}
```

**Comment by Tijn1974** [comment]
I did add a extra line to the manifest file
—> “version”: “1.0”,

1) in the clean installation of HomeAssistant 2021.6.4, the error has disappeared, there is only a orange announcement in the log about not tested with HomeAssistant, and possible …blablablabla.
The only thing problem is that the “tech” is not in the add-on list to add it.

2) when I take a old version of HomeAssistant like 2021.3.2, I can install the “tech” add-on. When I upgrade the HomeAssistant to 2021.6.4 and add the “version” line in the manifest file, it is working, with only the orange message in the log about not tested etc.

so, for me it is working now, just upgraded to 6.5. It only could be difficult for new users or people who start from a fresh 2021.6.4 version to install the tech add-on.

thanks for the help. I will close tomorrow this case

**Comment by Vittaly76** [comment]
Yes, I have absolutely the same problem. But unfortunately I have removed the integration, and now I can't add it again. (Also I have added version in manifest file, but it doesn't help. So, the problem is actual. At list for me :)

**Comment by Tijn1974** [comment]
Oh crap, ….. I also had removed it, but I could set a backup back of a older version.  I hope they can fix the intergration soon. Do you see something in the home-assistant.log file?

**Comment by Vittaly76** [comment]
> Oh crap, ….. I also had removed it, but I could set a backup back of a older version. I hope they can fix the intergration soon. Do you see something in the home-assistant.log file?

Mmm, nothing interesting. Only this:
`2021-06-17 09:39:34 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tech which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

But there is some magic here: today morning I have tryed to find this integration one more time, and this time everything is ok! So, my problem solved.

**Comment by Tijn1974** [comment]
Oh good one, …. Maybe some fairy 🧚‍♀️ did come.

**Comment by mariusz-ostoja-swierczynski** [comment]
Thank you guys for sharing this. I will update main branch once I find some free time.

Cheers, Mariusz

**Comment by alevike** [comment]
looks like it's not a simple missing version line from the manifest.json. 

After i've put the version line i get the next error in the logs: 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.tech-controllers.media_source'
2021-06-17 16:14:08 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing tech/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.tech-controllers.logbook'
2021-06-17 16:14:08 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing tech/group.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.tech-controllers.group'`

I'm still trying to understand what happening - it is looking for files which are not exists (yet) - logbook.py.

**Comment by Tijn1974** [comment]
Did you place all te files in the directory 'custom_components.tech-controllers’ ?

I thought all files needed to be placed in the directory ‘custom_components.tech’

**Comment by alevike** [comment]
no, i’ve edited only the json file, with those additional 2 lines(version
and cloud connection). everything else remains the same.

**Comment by Tijn1974** [comment]
Try to rename the directory name, if you look in the Json file, there is also written “tech” as directory and on the wiki page on this site it’s the same.

**Comment by alevike** [comment]
This is how it works fine for me:

{
  "domain": "tech",
  "name": "Tech Controllers",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/tech",
  "version": "0.0.1",
  "requirements": ["tech"],
  "dependencies": [],
  "codeowners": [
    "@mariusz.ostoja-swierczynski"
  ],
  "iot_class": "cloud_polling"
}

**Comment by jontofront** [comment]
> Thank you guys for sharing this. I will update main branch once I find some free time.
> 
> Cheers, Mariusz

Hi,
When it will be?

**Comment by mariusz-ostoja-swierczynski** [comment]
@jontofront  This is finally done in dev branch. Please test it out and report any issues. I will marge is to master hopefully soon.

Few words of explanations it took so long. During the development of this feature I was trying to get some simple support from Tech (answer on their APIs), but they didn't provide it although they promised it. After long time of reminding myself to them, winter was over and I lost both time and motivation. This winter I found out how many people were interested in this integration and even some people put effort for further development of this integration and so I regained bit of motivation. Anyway I don't have anything against forking this repo and moving forward if I lost it again :)
