### ISSUE TITLE
No entites due to setTemperature = None

### ISSUE THREAD

**Issue by mariusz-ostoja-swierczynski** [mariusz-ostoja-swierczynski/tech-controllers#6]
Logger: homeassistant.components.climate
Source: custom_components/tech/climate.py:54
Integration: Klimat (documentation, issues)
First occurred: 21:16:09 (1 occurrences)
Last logged: 21:16:09
Error while setting up tech platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tech/climate.py", line 32, in async_setup_entry
[
File "/config/custom_components/tech/climate.py", line 33, in <listcomp>
TechThermostat(
File "/config/custom_components/tech/climate.py", line 54, in __init__
self._target_temperature = device["zone"]["setTemperature"] / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by mariusz-ostoja-swierczynski** [comment]
I has been preported that fix works, but still there is error log during entity update:

homeassistant.components.climate
Source: custom_components/tech/climate.py:116
Integration: Klimat (documentation, issues)
First occurred: 7:25:51 (3 occurrences)
Last logged: 7:25:51
tech: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 357, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
await task
File "/config/custom_components/tech/climate.py", line 116, in async_update
self._target_temperature = device["zone"]["setTemperature"] / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by mariusz-ostoja-swierczynski** [comment]
It has been reported that now it gives following error:

2020-11-21 13:40:25 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform tech
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 505, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 221, in state_attributes
self.current_temperature,
File "/config/custom_components/tech/climate.py", line 129, in current_temperature
return self._temperature
AttributeError: 'TechThermostat' object has no attribute '_temperature'

**Comment by mariusz-ostoja-swierczynski** [comment]
It has been reported by users on FB page "Home Assistant Polska" that now the issue is fixed and there is no errors in the logs.
